<form class="form" action="?page=admin_login" method="POST">
    <div class="form__i">
        <div class="form__row">
            <label for="login">Login</label>
            <input type="text" id="login" name="admin[login]" required>
        </div>
        <div class="form__row">
            <label for="password">Password</label>
            <input type="password" id="password" name="admin[password]" required>
        </div>
        <input class="submit" type="submit" value="Auth">
    </div>
</form>