<ul class="product-list">
    <?php foreach ($this->get('quoteItemsByUser') as $_quoteItem): ?>
    <?php $_product = new \App\Model\Product([], $this->get('productResource'));
        $_product->load($_quoteItem->getProductId());
        ?>
        <li class="product-item">
            <a class="link-to-view" href="?page=product_view&id=<?php echo $_product->getId()?>">
                <div>
                    <img class="preview-image" src="<?php echo $_product->getImage(); ?>" alt="Preview"/>

                    <h2 class="name"><?php echo $_product->getName(); ?></h2>

                    <p class="sku">SKU: <?php echo $_product->getSku(); ?></p>

                    <?php if ($_product->isSpecialPriceApplied()): ?>
                        <p class="price price-strike">
                            <s><?php echo $_product->getPrice(); ?>$</s>
                        </p>
                        <p class="special-price"><?php echo $_product->getSpecialprice(); ?>$</p>
                    <?php else: ?>
                        <p class="price">
                            <?php echo $_product->getPrice(); ?>$
                        </p>
                    <?php endif; ?>
                </div>
            </a>
            <div class="count-view">
                <span><?php echo $_quoteItem->getQuantity(); ?></span>
            </div>
            <form class="entity-doing" action="?page=cart_changeCount" method="POST">
                <input type="text" name="product_id" value="<?php echo $_product->getId(); ?>" hidden>
                <input class="entity-doing__add" type="submit" name="action" value="Add">
                <input class="entity-doing__count" type="number" name="count" value="1" min="1" max="99">
                <input class="entity-doing__remove" type="submit" name="action" value="Remove">
            </form>
        </li>

    <?php endforeach; ?>
</ul>