<form class="form" action="/?page=checkout_address" method="post">
    <div class="form__row">
        <label for="region">Region:</label>
        <select name="address[region_id]" id="region">
            <?php foreach($this->get('regions') as $_region): ?>
            <option value="<?php echo $_region->getId(); ?>"><?php echo $_region->getName(); ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="form__row">
        <label for="city">City:</label>
        <select name="address[city_id]" id="city">
            <?php foreach($this->get('cities') as $_city): ?>
                <option value="<?php echo $_city->getId(); ?>"><?php echo $_city->getName(); ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="form__row">
        <label for="postalCode">Postal code:</label>
        <input type="text" name="address[postal_code]" id="postalCode">
    </div>
    <div class="form__row">
        <label for="street">Street:</label>
        <input type="text" name="address[street]" id="street">
    </div>
    <div class="form__row">
        <label for="home">Home:</label>
        <input type="text" name="address[home_number]" id="home">
    </div>
    <div class="form__row">
        <label for="flat">Flat:</label>
        <input type="number" name="address[flat]" id="flat">
    </div>
    <div class="form__row">
        <input type="submit" value="Send">
    </div>
</form>