<form class="customer-form" action="?page=customer_login" method="POST">
    <div class="customer-form__i">
        <div class="customer-form__field">
            <label for="login">Login</label>
            <input type="text" id="login" name="customer[login]" required>
        </div>
        <div class="customer-form__field">
            <label for="password">Password</label>
            <input type="password" id="password" name="customer[password]" required>
        </div>
        <input class="customer-form__submit" type="submit">
    </div>
</form>