<?php $session = new \App\Model\Session(); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Student Webstore</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/css/layout.css"/>
    <link rel="stylesheet" href="/css/<?php echo $this->get('css'); ?>.css">
</head>
<body>
<header class="header">
    <div class="customer-panel">
        <span>Hi, <?php echo $session->isLoggedIn() ? $session->getCustomer()->getName() : 'guest'; ?>!</span>
        <?php if (!isset($_SESSION['customer'])): ?>
            <a href="?page=customer_login">Login</a> |
            <a href="?page=customer_register">Sign Up</a>
        <?php else: ?>
            <a href="?page=customer_logout">Logout</a>
        <?php endif; ?>
        | <a href="?page=cart_list">My Cart</a>
    </div>
    <h1><?php echo $this->get('header'); ?></h1>
</header>
<?php if ($this->get('view') != 'product_list'): ?>
    <nav class="back-to-product-list">
        <a href="/?page=product_list">←</a>
    </nav>
<?php endif; ?>
<section class="content">
    <?php $this->renderTemplate(); ?>
</section>
<footer class="footer">
    <p class="copyright">© 2013 Eduard Paliy</p>
</footer>
</body>
</html>