<!DOCTYPE html>
<html lang="en">
<head>
    <title>Student Webstore | Page Not Found</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/css/page_not_found.css"/>
</head>
<body>
<header class="header">
    <h1>Student Webstore | Error 404</h1>
</header>
<section class="content">
    <h2>Page not found. We are sorry</h2>
    <a href="/">Try go to the mainpage</a>
</section>
</body>
</html>
