<ul class="product-list">
    <?php foreach ($products as $_product): ?>

        <li class="product-item">
            <a class="link-to-view" href="?page=product_view&id=<?php echo $_product->getId()?>">
                <div>
                    <img class="preview-image" src="<?php echo $_product->getImage(); ?>" alt="Preview"/>

                    <h2 class="name"><?php echo $_product->getName(); ?></h2>

                    <p class="sku">SKU: <?php echo $_product->getSku(); ?></p>

                    <?php if ($_product->isSpecialPriceApplied()): ?>
                        <p class="price price-strike">
                            <s><?php echo $_product->getPrice(); ?>$</s>
                        </p>
                        <p class="special-price"><?php echo $_product->getSpecialprice(); ?>$</p>
                    <?php else: ?>
                        <p class="price">
                            <?php echo $_product->getPrice(); ?>$
                        </p>
                    <?php endif; ?>
                </div>
            </a>
            <form class="add-to-cart-form" action="?page=product_addToCart" method="POST">
                <input class="add-to-cart-form__product-id" type="text" name="product_id" value="<?php echo $_product->getId()?>" hidden>
                <input class="add-to-cart-form__submit" type="submit" value="Add One To Cart">
            </form>
        </li>

    <?php endforeach; ?>
</ul>