<?php $_product = $this->get('product'); ?>
<div class="product-info">
    <section class="product__details">
        <img class="product__preview-image" src="<?php echo $_product->getImage(); ?>" alt="Preview"/>

        <h2 class="product__name"><?php echo $_product->getName(); ?></h2>

        <p class="product__sku">SKU: <?php echo $_product->getSku(); ?></p>

        <p class="product__price__wrap">
            Price:
            <?php if ($_product->isSpecialPriceApplied()): ?>
                <span class="product__price product__price_strike">
                <s><?php echo $_product->getPrice(); ?>$</s>
            </span>
                <span class="product__price_special"><?php echo $_product->getSpecialprice(); ?>$</span>
            <?php else: ?>
                <span class="product__price">
                <?php echo $_product->getPrice(); ?>$
            </span>
            <?php endif; ?>
        </p>
        <form class="add-to-cart-form" action="?page=cart_addToCart" method="POST">
            <input class="add-to-cart-form__product-id" type="text" name="product_id" value="<?php echo $_product->getId()?>" hidden>
            <input class="add-to-cart-form__submit" type="submit" value="Add One To Cart">
        </form>
    </section>
    <section class="review-list">
        <header class="review_list__header">
            <h2>Reviews</h2>
        </header>
        <ul class="review-list__i">
            <?php foreach ($this->get('reviews') as $_review): ?>
                <li class="review">
                    <h3 class="review__header">
                        <p class="review__name"><?php echo $_review->getName(); ?></p>

                        <p class="review__rating">
                            <?php for ($i = 0; $i < $_review->getRating(); $i++): ?>
                                ★
                            <?php endfor; ?>
                            <?php for ($i = 0; $i < 5 - $_review->getRating(); $i++): ?>
                                ☆
                            <?php endfor; ?>
                        </p>
                    </h3>
                    <p class="review__text"><?php echo $_review->getText(); ?></p>
                </li>
            <?php endforeach; ?>
        </ul>
        <nav class="pagination">
            <ul class="pagination__list">
                <?php for ($page = 1; $page <= $this->get('pages')->pageCount; $page++): ?>
                    <?php if ($this->get('pages')->current == $page): ?>
                        <li class="pagination__item pagination__item_current">
                            <span><?php echo $page; ?></span>
                        </li>
                    <?php else: ?>
                        <li class="pagination__item">
                            <a href="/?page=product_view&id=<?php echo $_product->getId(); ?>&p=<?php echo $page; ?>">
                                <?php echo $page; ?>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endfor; ?>
            </ul>
        </nav>
    </section>
</div>