<div class="product-info">
    <section class="product__details">
        <img class="product__preview-image" src="<?php echo $product->getImage(); ?>" alt="Preview"/>

        <h2 class="product__name"><?php echo $product->getName(); ?></h2>

        <p class="product__sku">SKU: <?php echo $product->getSku(); ?></p>

        <p class="product__price__wrap">
            Price:
            <?php if ($product->isSpecialPriceApplied()): ?>
                <span class="product__price product__price_strike">
                <s><?php echo $product->getPrice(); ?>$</s>
            </span>
                <span class="product__price_special"><?php echo $product->getSpecialprice(); ?>$</span>
            <?php else: ?>
                <span class="product__price">
                <?php echo $product->getPrice(); ?>$
            </span>
            <?php endif; ?>
        </p>
        <form class="add-to-cart-form" action="?page=product_addToCart" method="POST">
            <input class="add-to-cart-form__product-id" type="text" name="product_id" value="<?php echo $product->getId()?>" hidden>
            <input class="add-to-cart-form__submit" type="submit" value="Add One To Cart">
        </form>
    </section>
    <section class="review-list">
        <header class="review_list__header">
            <h2>Reviews</h2>
        </header>
        <ul class="review-list__i">
            <?php foreach ($reviews as $_review): ?>
                <li class="review">
                    <h3 class="review__header">
                        <p class="review__name"><?php echo $_review->getName(); ?></p>

                        <p class="review__rating">
                            <?php for ($i = 0; $i < $_review->getRating(); $i++): ?>
                                ★
                            <?php endfor; ?>
                            <?php for ($i = 0; $i < 5 - $_review->getRating(); $i++): ?>
                                ☆
                            <?php endfor; ?>
                        </p>
                    </h3>
                    <p class="review__text"><?php echo $_review->getText(); ?></p>
                </li>
            <?php endforeach; ?>
        </ul>
    </section>
</div>